#include "string.h"
#include "include/payload_gen.h"

struct request {
	int req_type;
	unsigned int payload_length;
} __attribute__((__packed__));

/* #define PAYLOAD "hello world this is a messageZ\n" */
//
#define PAYLOAD "dvfhshtkqtyuuujawsufsn\r\n"
// 64
/* #define PAYLOAD "duafmnhwvfhshtkqtyuuujawsufsngvnopyvesdyvaoifzbviwrglaonrxkaaaEND\r\n" */
// 256
/* #define PAYLOAD "duafmnhwvfhshtkqtyuuujawsufsngvnopyvesdyvaoifzbviwrglaonrxkjfjiuduafmnhwvfhshtkqtyuuujawsufsngvnopyvesdyvaoifzbviwrglaonrxkjfjiuduafmnhwvfhshtkqtyuuujawsufsngvnopyvesdyvaoifzbviwrglaonrxkjfjiuduafmnhwvfhshtkqtyuuujawsufsngvnopyvesdyvaoifzbviwrglaonrxkaaaZ\n" */
// 1024
/* #define PAYLOAD "cgnjujxeddpaygqnnsgtudrwcgnjujxeddpaygqnnsgtudrwzfktizfizldhgjolttogrxjusdycsfrxagtoidkpqxfbxgallrsawhalmylvxfhfckzgdyqrztghsuofuhavmmwcneffzjsqkustyabklzvgpcmozxaywliqokepihtphywcvoowcimwkpomqxntaqxuyyndrsrdcaiayddgmlgisyslyklekqspbmhnsiifkdgatbxudeylvmcvjxltldrnunmnjyhrawoswyvttvieazsixoassuookghuggwidwcqzfvfkmjacvbokhyrczztdowmaqhgfwrlhrvrjumllmrtybthprehcvbzqiaxgnvmahktkhupprksuvtxiudneryzavfrxhqygobpofynvqcuhkqlnmflyyyhqqfmqrzjiusiuchibcahnmigvziqkixfmxwyljpwagnksbocvqlxhtscpgrftiphctnirekqtfxnbfvlqgtlnespqhrbgreusufmobrymqirkofqpiherzyuwimkkovrtdieebmkwgehxhvfdkovbpaiepgjvopganiqudellhasnapumtipsyqshjlslsjjovzamlrscwzvdaoyrvkbrlrlytijfbkvrmaasvrqqunzjkxehwdpshpzsvlccnrkmwecmzvileyshzknbubbehdmzinxtyebgrpivngltxlfgluvabarlmvptdxfddnjxuikvzswiryuryvaajvzqbakvqprbkjgaoyrflhsltpigrpfeqyxitzoniicoesewdohtdxqtjnbyyqcbbegslmwavwtxqteeioojuvdonipdalwgnmxghaoafswnvikzztsfwytfmrzziaqtmjlqszdvuipcwkwlueflkjtdfduospyjffgzbhxtspaqozpkszfflfbgvndpsznyscizcjvvzdakxjukituktymprffwtaikmfiffmkjycqzyetgwrvbuwzaitbgyrvkeziZ\n" */
// 2048
/* #define PAYLOAD "zcldttzegdkopnymcbjdzbvbpjzrrwlefixknmcnxascfafdzcldttzegdkopnymcbjdzbvbpjzrrwlefixknmcnxascfafdgrllkmhssamxecfcskvpnlgozuagealltpyysjsjtexrhyezgqvioqvtzojlehwgigucstszvzqhvghnbsvaqjegrypchtsvubpcxmgapunfserpuxgtujglfccneikslbznddrwncmpompyumkkvxjifxdjsnaajresgewygcnbeabbfsllkljansrgllycitebxtyprufwyscblkqpxgeaxcwrnieuvpzguycxogbhzhfgymgmjfbqhkvctooynzguuzsflkbdkmscvnylknrzlmjtrroezmxkziotgqllzrzkolpeivvtkpzikepagjpxumqamziwcffvgcsbllmaawxytfxemjpcffboldzxqmfquwilbyythnxzfhgdfnmgossutjqymzcegyrtddmbcstkapvuonugvuwmkbrehwlfqfogwktdemcskctoqyborrviwciyzqrnjcjipvwrbofjviagfyngyjgxgmsleofwuiqwzdxqslybhvkdundqxnufnsenpkegsspeufteavznxersnyaoaskyrhnxhqxuqbjgxqwihpjoggotccoogroebovynowhnlpxrjspussnkyznjxjpevabfnimhydyxhszqhvypqknhkhyvbbebsyzutijwqggcmmszsptbsfgjnldfkuzfflrcddprsnpnqkxikvysrpqilrkowmnhdaftajnmwumuylnvstlpmgismhjuhckmnfvhbtbubjnwmmenaxsikyfmmqybnakiafdubmqozckdmiwvxdtflqancrhsqzegbkvbqxidbiaxvceqdpbnyarinffatlnovzmfvisijlzqaummzevjbifbbdbmlzptvbhbtkojapztstavtemcrlselpnskncqjrjiysjncwfigwiivcezeqddnmuntrqnrdkwllnkwsorxchztfnwlwwrkuiglgknhtauqwrusozgbekuzhmnnxexeyqjkwqnmiphyzwwsmuolzwglwikgqxgcwxewhspuwkhzpxsmijgiwwjzqnvgfqpiscwxtlrjdiktfhhafsikbrtujuwyyruunsmmtjdmjyimxkydmxzcdyiiunasvhfthwstoakgttykijzjmmznzpdndqspubboyovsgyxvxxfrydgfphfjatbfaeppiwrmenuuzzpxuwbmtihinawqffgnwjyfavuajibrzctzvkofgdpgtwebibtbgroqptfxhefonfszgzpubjllgwpdhcirwoqjubftwjsezigriflidmvvhnrgnsbddgbwrymopzskcvgimiskgcaxohcgdmqqxgieuetirvqrfrvhzmxwruemjjpchjiselsttmzrqixqdgpgabzejcuphjkcpfqryevhlyakcuehsajqjypkpsgyfrbvfxeodnvppuxjyqmclwdjmiryrluotrkjrckognkxkmoibcwzkbsadkqakvcvcfczdkcxbvdnnqvsctgsoiagwinohoysxqfkcsyzhrqyetifldlffgodgyqlylrbgfuaxkhamgmyxalyfmvkcsymatrvzsgdiaforfvikyvgfnktfzjnscebifchhhkflznkbsjbslhmvhkpxjfvgjfnhaueqmdvgjidamoolerinprjbbyodtcrjlhgcehdvupzixbenqfihepvoodesbrhemxyqylynnlmykrpmwejyyooibrhrexibzakfuifujdiutveqyqsndhihdrxezwufctwniiluiievyqptckqqhsahlcpevhvbylcntirmalzjkezboozcykakvimdhkdssgrgkrdvuaeohyjzhzpdbsjciifedkysueknhkncdsoaajuqcjhrkvsygvlzpfbdwcmnrfowpzdvrrxoeaupmvdfuspprxpkvmxayghlmehoiydtcplmiqrdzZ\n" */
// 4000
/* #define PAYLOAD "omqeoxqmuuvdijcqdqzrafnfazmryceqevbznxgsoyrhfurdexwtzxascfwwvseyajzsxcncwgumqgkjzqgcfbhlccwnkoarbacsacudpvrdnipsshlutpemklpbegjzorsnxdzfjofagitgprcovdeeuwdqbnpjtvowhrlkttqlffgmcdulupnqdrpeprvhclbdcfjunmzqhwwxtzztgltoplgjyfnvpzturwcygkddtmduaelbpmbnsxzsxvuzifqaysdpdokhppqgbslbfwvzpdfhzfweicoxlcuikbqgysycdlkhfesgfnlnzdaozlgiqzcveqtpbeggrfnzvdjlogpujjlgrdeyjabwvhzunxhjrksvydbkjkjcxiqpbvggyunrawuefqfritotdslfmvhtgmnzorgjqqpgcqsfjpizpiodaulmnncvashhbbdraaffdcflivedfqorblcinlifdajnfzszkrkwxclrvnlbgumdtnbqnnyvplzqindahsftnpqfhnrmywbqcfxqyrsgoiibbtnivhifoinovhaxkbftrjgdwjlvgovnhkfdjhnrhaqiwdprgxwylylmgnaoqumylaieejtvnpizyysdhhsbxwghhmgngyuhsscewjndsakwwlaqtwznnknynyjmmbnqtrjqgximheuvqooybnwmolvleabmdhlheblfwpwiczliirydvimruapnpmvbjkswhuwenccizvebzmjurhgaogxedqdhqneulwoxaxkwtjktzlwlnwexcndpleyslntagxehoulxpmjqvkroqblbbcdcbsgzelrbwtbniuxgvlehtfdjryvgrrhfjlzionihvpecmftzigutyxldsosjmdtgnoazmmeyvrdstznsyyssppmgmjxheqpqemwwavkvajplomnotpfrqkjmcoyusndywespdpytakwhekvxjdetvirydclzofaqxpxzirhzspifpjapgzaaetyouanhilmjibbfgraukrodviogbjlbcpmboefykjicwymahvnrrivmpkldqglmjhghobitrtfakgklwnaatcjkckkrysofziofavnufvalderskyhypifkshljqxtzehajlxfwivrquhpmleccdqnplmfoypzlettrgwcrcwscqgixtownrfvdrpnbxqebuzooqwmreiiexsbkjvuekvlvioxukicyfglavmmgfwgudtxsxzlqyfyufhdsqnfjoejjmduofqupuhgcaiqoizjjiylbijmvjdgkwkplpqlvzqsddptqikykjtrdtgigtpulvotsbjsxueueedeqbzyqbrgmvrhobqosqiqgkllablqjugdmfosthbnptdfsmyvwagyuxygaulljiyzydjcslvbwdcrslrflxrrrpgdicnmeguwbsaplutxlizxeuijuzeimmsrsynvcyhdyubriknnozbatslretkmunxijrbfoyznbqdlkusdwpgutlhoqxigfrxdkqxvlptnqsnxicmvodfggckiwllkvvqcymirablkxnpfnmjahbaxgjlfouugiwcppxpduvxlfnkqnqltwldlzkdrrfkwtvwzjuzfunxaktiiyldubowpxfybtibjiscpwdlhkahzmsrjrbtqnolvxxviojulgymzjtecdpmokdklzjnnsqmqweuckkpceqgvtjwiovggbqudjykammgykqlsbcqojupjsmrrtjpfbnxrojdbxtcqnybmoupnmmlncfdxpuwnkhggjlkispbqbwzlballyfyajpytcpbonjznlmbjlscxjhynjxvwolruifmyibqlxhirehgrrseqejxrnryoykolyarowieuvyjblhwfdqxizjqczhnekxdsaoqxusgtiowxsqgtaqzwzlojmppttvoaqvkhpnfrgdgtqavogjqojyeopqotnumhbaaqnpejklyvfihjanwdjwzavwrpsdpdkzhnaikpdpalhbrgogitvpcrqworwpcjcbodqoynlkozeehphzwbqvcocxuarqxzhjnqufjbpouwfbzqvoxeyyapercusneuohstpgtxzytzbivcngwlybpuyffictcvdehsrlwfsnhpsgsubtlhpwibhczipgrgnplkvvyvkbattnzwydzkyexljdpgfplquknpjkvmpcvsuyhxkkpzysikhvtqpcdeuoldfoiibxtnyrpyllzdjdigstvustntygjyuvbtsbcwlfxrlsgjirkltyshehlioppcmkfiukbakszcmmokckaihxtkzjtmzezqzzicvawioojvwullttlopungmdvzqbkfkpnatbslknakliihnypeoevmlhaidfbaknogpzwqwzhpsbitmvtpdxktudblzrvjiqpbvifzxafxjpsfwoiqujnagbbsllgapjbrnujcnvmdmhbelwcanvctxxonbgeuhvyfxpfexdpxvtpiedcjresgvkiugixdvpuafncbuqadgzzewdyqfoycubytbljnvekzmpqfvqxehwtfuamghajuavgamahlhyetzprqjssoquijltazoqwapcfddxauhrxzwerrdlnlmlphmqnowfbsivhfrttaobbvwtaasfzkdxcrjcwlqzxhonvphwjfmskvcwfsviqqdixpvogjvfgrhebuunpbmmtgakwxyymielliptlxhveyvggqtdhxmbdmgmszilnybqpjycikulltkmsggbzwhxpvfiejsgwnieptjlbybggarvoltntwnescbbpkcpixmlnzffkdolinolmvoruvosaifqyaehotyyvczjavzmjoevwmvejrzzzgbzhtawhhotcrzffhzouhhojpbixaqiuwgmxvhpahlwinohhywpclemogwgmdaoxdsgaphjlcsxozlogucfgboxnyfgsafcxmmojnjuhlgxlqkgeixbygqwxyonjcmpqqddtumeankctslhmpjjizojnvzlsoyutaywstgezwtwdsqkxitlpnkjzcnqjrykthylscotxeppsohtwqflfigpdlxeditycvwyymdttkjhjpxydikjolnjnjhnlbmdiowbpkroaliajispqxaogpbnsxqnvcwxkevnfiznofrcvrqevjctiewrqcnqrwwtndxuxckoiixtiazunnvnaukrksunebcuolbxltfppeulfcajzyqvzmidnbtzvvgeyptnjfvdlqjlkjqcciwdumiohdolzwboebbcjfhdophhebpijfczovbqlnjpukbyzyyyujljrttqtllytpxobhicnfasvolvqeoijhrwdyrhdrtnwzvlksjyvnbcxfwkfyadcoaijeecmkhxjziwyiyudfsebutygbrjpfameanahcbxkjtjejjgawfxmoexxxndfsvruaetweveitmadwthzzgaljemantxgcsrqglvbienaoqvxjwjkmkppkruqdprndqhemqlifiejhcddjnynpkintxmiijqmbrasrdyvowrvflrlqeggxfyptqonmznxczswwgsdehwmqcfxkeoabrdawucsqdvdaefyylyqbfcgbhtknepugymsxthcxydcprpzbnhedfxiaqzftlyztamqgerzvvayfwbeexqlsfzdhdadvoyuadeutsiibeoiwflsikxwzozohvkvvcbsavbnitcbvzstbomarbpswyjnlydwdytkpexoiengotngumfboiqgxyqzuzhucndjqpttxpmudrtnxjjmjxlriegfexcbqxeeslbbzfszsbytdcguxocohcffemojuekrkqfhjbzfydvpnawnfvufbnhjerxzeqymlfukszkxbwqkbziycoydmokoeapeetyfpcwbrfmrypivqeimbsygfiuofapyiyfupacnwvkscdvpdrnfpfxwrxpssoihxkzjzgddcaaaZ\n" */
#define PAYLOAD_SIZE (sizeof(PAYLOAD)-1)
int prepare_request(void *buf, int len)
{
	struct request *header = buf;
	char *payload = (char *)(header + 1);

	/* TODO: make this configurable */
	/* NOTE: Hard coded protocl */
	header->req_type = 2;
	header->payload_length = PAYLOAD_SIZE;
	memcpy(payload, PAYLOAD, PAYLOAD_SIZE);

	/* How many bytes to send (header + payload) */
	return sizeof(header) + PAYLOAD_SIZE;
}

int prepare_request_inc_num(void *buf, int len)
{
	// TODO: assuming len is at least 4 bytes
#define MAX_NUM 2000000
	static int last_num = 0;
	*(int *)buf = last_num;
	last_num = (last_num + 1) % MAX_NUM;
	return 4;
}

